apiVersion: v1
kind: Service
metadata:
  name: argocd-external
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
  ports:
    - port: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - argocd.dev.ajoufesta.com
      secretName: wildcard-ajoufesta-cert
  rules:
    - host: argocd.dev.ajoufesta.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: argocd-external
                port:
                  number: 80