apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-ajoufesta-cert
  namespace: ingress-nginx
spec:
  dnsNames:
    - '*.dev.ajoufesta.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: wildcard-undercloud-prod-cert

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ajoufesta-cert
  namespace: ingress-nginx
spec:
  dnsNames:
    - 'dev.ajoufesta.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: undercloud-prod-cert